### ISSUE TITLE
Maze found at https://django-indieweb.readthedocs.io

### ISSUE THREAD

**Issue by kwill** [ephes/django-indieweb#1]
The README and PyPI page point to https://django-indieweb.readthedocs.io but that page doesn't exist.

**Comment by ephes** [comment]
Ups, thanks - fixed it. But there's not much documentation  there anyway. I think the auth and token endpoint are working, but the micropub endpoint doesn't do anything useful yet. So [https://indieweb.org/IndieAuth](indieauth) should be possible. It took me some time to understand how this should work and [https://indieweb.org/obtaining-an-access-token](this overview) helped me a lot. There's some [https://github.com/bear/python-indieweb](code for flask) doing a similar thing and it's much more complete. Maybe I get back to this project soon, since I'm working on a personal blogging platform for django which could benefit from a micropub endpoint..

**Comment by kwill** [comment]
Thanks! Still getting into it so it's great to have a reference point (even incomplete).
